# Generated by Django 5.2.4 on 2026-03-10 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def sync_approval_status_from_legacy_status(apps, schema_editor):
    Accomodation = apps.get_model('admin_app', 'Accomodation')
    for accom in Accomodation.objects.all().only('accom_id', 'status', 'approval_status'):
        legacy = (accom.status or '').strip().lower()
        if legacy in {'pending', 'accepted', 'declined'}:
            accom.approval_status = legacy
            accom.save(update_fields=['approval_status'])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0024_room_price_per_night'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodation',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_accommodations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(sync_approval_status_from_legacy_status, noop_reverse),
    ]
