# Generated by Django 5.2.4 on 2026-03-11 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0025_accomodation_approval_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TourismInformation',
            fields=[
                ('tourism_info_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('spot_name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=300)),
                ('contact_information', models.CharField(blank=True, default='', max_length=255)),
                ('operating_hours', models.CharField(blank=True, default='', max_length=255)),
                ('publication_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tourism_information/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tourism_information', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tourism_information', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tourism Information',
                'verbose_name_plural': 'Tourism Information',
                'ordering': ['spot_name', '-updated_at'],
            },
        ),
    ]
