# Generated by Django 5.2.4 on 2026-03-16 06:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0026_tourisminformation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accomodation',
            options={'ordering': ['-submitted_at', 'company_name']},
        ),
        migrations.AddField(
            model_name='accomodation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_accommodations', to='admin_app.employee'),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='company_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='company_type',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='location',
            field=models.CharField(db_index=True, max_length=300),
        ),
    ]
