# Generated by Django 5.2.4 on 2026-03-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0027_alter_accomodation_options_accomodation_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accomodation",
            name="accommodation_amenities",
            field=models.TextField(blank=True, default=""),
        ),
    ]

