# Generated by Django 5.2.4 on 2026-03-31 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accom_app', '0020_authoritativeroomdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other_estab',
            name='intended_month',
            field=models.CharField(default='March', max_length=20),
        ),
    ]
