# Generated by Django 5.2.4 on 2026-04-09 09:27

import accom_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accom_app', '0021_alter_other_estab_intended_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other_estab',
            name='intended_month',
            field=models.CharField(default=accom_app.models.current_month_name, max_length=20),
        ),
    ]
