# Generated by Codex on 2026-03-11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("guest_app", "0032_accommodation_booking"),
    ]

    operations = [
        migrations.CreateModel(
            name="Billing",
            fields=[
                ("billing_id", models.AutoField(primary_key=True, serialize=False)),
                ("booking_reference", models.CharField(max_length=30, unique=True)),
                ("total_amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("unpaid", "Unpaid"), ("partial", "Partially Paid"), ("paid", "Paid")],
                        default="unpaid",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Not Set"),
                            ("cash", "Cash"),
                            ("gcash", "GCash"),
                            ("bank_transfer", "Bank Transfer"),
                            ("card", "Card"),
                            ("other", "Other"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("amount_paid", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("billing_date", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing",
                        to="guest_app.accommodationbooking",
                    ),
                ),
            ],
        ),
    ]
