# Generated by Codex on 2026-03-11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("guest_app", "0033_billing"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccommodationBookingCompanion",
            fields=[
                ("companion_id", models.AutoField(primary_key=True, serialize=False)),
                ("companion_name", models.CharField(max_length=120)),
                ("companion_contact", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companions",
                        to="guest_app.accommodationbooking",
                    ),
                ),
            ],
            options={
                "ordering": ["companion_id"],
            },
        ),
    ]
