# Generated by Django 5.2.4 on 2026-03-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0029_rename_sced_id_to_sched_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour_add',
            name='publication_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='published', max_length=20),
        ),
    ]
