# Generated by Django 5.2.4 on 2026-03-25 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0030_tour_add_publication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour_event',
            name='event_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='Tour_SupportingImage',
            fields=[
                ('support_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='tour_images/supporting/')),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_images', to='tour_app.tour_add')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
